version: '3'
services:
  postgres:
    container_name: elicelab_reservation_postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
    networks:
      - elice_network
  redis:
    container_name: Kangho_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6380:6379"
    networks:
      - elice_network
  nestjs:
    container_name: elicelab_reservation_nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - elice_network
    volumes:
      - .:/app

networks:
  elice_network:
    driver: bridge