services:
  elicelab_reservation_nginx:
    image: nginx:stable-alpine
    container_name: elicelab_reservation_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - elicelab_reservation_nestjs
    networks:
      - elice_network

  elicelab_reservation_nestjs:
    container_name: elicelab_reservation_nestjs
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - elicelab_reservation_postgres
      - elicelab_reservation_redis
      - elicelab_reservation_minio
    networks:
      - elice_network



#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    depends_on:
#      - elicelab_reservation_postgres
#      - elicelab_reservation_redis
#      - elicelab_reservation_minio
#    networks:
#      - elice_network
#    volumes:
#      - .:/app
  elicelab_reservation_postgres:
    container_name: elicelab_reservation_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - elice_network
  elicelab_reservation_redis:
    container_name: elicelab_reservation_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - elice_network
#  minio:
##    image: docker.io/bitnami/minio:2022
#    container_name: elicelab_reservation_minio
#    image: minio/minio:latest
#    command: server /data --console-address ":9001"
#    env_file:
#      - .env
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    volumes:
#      - ./data:/data
##    networks:
##      - elice_network
  elicelab_reservation_minio:
    image: docker.io/bitnami/minio:2022
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '9001:9001'
    platform: linux/amd64
    networks:
      - elice_network

networks:
  elice_network:
    driver: bridge