version: '3'
services:
  postgres:
    container_name: elicelab_reservation_postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - .env
  redis:
    container_name: Kangho_redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6380:6379"